// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_transaction.sql

package database

import (
	"context"
	"time"
)

const addTransaction = `-- name: AddTransaction :one

INSERT INTO transactions (
    id, 
    ticker, 
    transaction_date, 
    transaction_price, 
    shares, 
    type, 
    username
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, ticker, transaction_date, transaction_price, shares, type, username
`

type AddTransactionParams struct {
	Ticker           string
	TransactionDate  time.Time
	TransactionPrice string
	Shares           string
	Type             string
	Username         string
}

func (q *Queries) AddTransaction(ctx context.Context, arg AddTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, addTransaction,
		arg.Ticker,
		arg.TransactionDate,
		arg.TransactionPrice,
		arg.Shares,
		arg.Type,
		arg.Username,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.TransactionDate,
		&i.TransactionPrice,
		&i.Shares,
		&i.Type,
		&i.Username,
	)
	return i, err
}
