// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id, created_at, updated_at, name, hashed_password)
VALUES (
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2
)
`

type CreateUserParams struct {
	Name           string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.HashedPassword)
	return err
}
