// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_return.sql

package database

import (
	"context"
)

const getReturn = `-- name: GetReturn :many

SELECT ticker,
SUM(CASE
    WHEN type = 'BUY' THEN shares
    WHEN type = 'SELL' THEN -shares
    ELSE 0 END)::DOUBLE PRECISION AS current_shares,

SUM(CASE
    WHEN type = 'BUY' THEN (shares * transaction_price)
    WHEN type = 'SELL' THEN -(shares * transaction_price)
    WHEN type = 'DIV' THEN -(shares * transaction_price)
    ELSE 0 END)::DOUBLE PRECISION AS cost_basis
FROM transactions
WHERE username = $1
GROUP BY ticker
`

type GetReturnRow struct {
	Ticker        string
	CurrentShares float64
	CostBasis     float64
}

func (q *Queries) GetReturn(ctx context.Context, username string) ([]GetReturnRow, error) {
	rows, err := q.db.QueryContext(ctx, getReturn, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReturnRow
	for rows.Next() {
		var i GetReturnRow
		if err := rows.Scan(&i.Ticker, &i.CurrentShares, &i.CostBasis); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
