// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_holdings.sql

package database

import (
	"context"
)

const getHoldings = `-- name: GetHoldings :one

SELECT
COALESCE(SUM (
    CASE 
        WHEN type = 'BUY' THEN (transaction_price * shares)
        WHEN type = 'SELL' THEN -(transaction_price * shares)
        WHEN type = 'DIV' THEN (transaction_price)
        ELSE 0
    END
    ), 0)::FLOAT AS total_holdings_value
FROM transactions
WHERE username = $1
`

func (q *Queries) GetHoldings(ctx context.Context, username string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getHoldings, username)
	var total_holdings_value float64
	err := row.Scan(&total_holdings_value)
	return total_holdings_value, err
}
