// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_companies.sql

package database

import (
	"context"
)

const getAll = `-- name: GetAll :many

SELECT id, ticker, transaction_date, transaction_price, shares, type, username FROM transactions
WHERE username = $1
`

func (q *Queries) GetAll(ctx context.Context, username string) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAll, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.TransactionDate,
			&i.TransactionPrice,
			&i.Shares,
			&i.Type,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
