// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_holding.sql

package database

import (
	"context"
)

const getHolding = `-- name: GetHolding :one

SELECT 
COALESCE(SUM (
    CASE 
        WHEN type = 'BUY' THEN shares
        WHEN type = 'SELL' THEN -shares
        ELSE 0
    END
    ), 0)::FLOAT AS total_holding
FROM transactions
WHERE ticker = $1 AND username = $2
`

type GetHoldingParams struct {
	Ticker   string
	Username string
}

func (q *Queries) GetHolding(ctx context.Context, arg GetHoldingParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getHolding, arg.Ticker, arg.Username)
	var total_holding float64
	err := row.Scan(&total_holding)
	return total_holding, err
}
