// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_shares.sql

package database

import (
	"context"
)

const getShares = `-- name: GetShares :one

SELECT shares FROM transactions
WHERE ticker = $1
`

func (q *Queries) GetShares(ctx context.Context, ticker string) (string, error) {
	row := q.db.QueryRowContext(ctx, getShares, ticker)
	var shares string
	err := row.Scan(&shares)
	return shares, err
}
